### ISSUE TITLE
Claim Bug

### ISSUE THREAD

**Issue by Some1gee** [SleepingTea98/Infinity-Modpack#2] opened 2019-04-02 20:33 UTC
I tried claiming the space around and including my reactor. Then to test, I had a different player who I had not trusted try to mine something at the base. The player came and was able to mine blocks around the claimed portion.

Image: http://prntscr.com/n6ln2y

**Comment by Some1gee** [comment] 2019-04-02 20:34
The image was from the player I asked to try to see if it would be able to be mined

**Comment by SleepingTea98** [comment] 2019-04-14 03:43
Dupe of an already known bug. Issue closed

**Closed** 2019-04-14 03:43 UTC
Labels: duplicate
